//This file has been autogenerated with the tool "ResourceDynamicConverterCreator". see the tool folder
//This file depends in "EnadlaInventory.UI.Strings.CodeErrorMessages"

using System;
using System.Windows.Data;
using EnadlaInventory.UI.Strings;

namespace EnadlaInventory.UI.Helpers.Mvvm{

    public class ErrorCodeMessagesKeyConverter: IValueConverter{
        
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture){
            string valueAsString = (string)value;

            if (valueAsString == "DIFERENT_CONFIRM_PASSWORD")
                return CodeErrorMessages.DIFERENT_CONFIRM_PASSWORD;

            else if (valueAsString == "EMPTY_EMAIL")
                return CodeErrorMessages.EMPTY_EMAIL;

            else if (valueAsString == "EMPTY_PASSWORD")
                return CodeErrorMessages.EMPTY_PASSWORD;

            else if (valueAsString == "EMPTY_VALUE")
                return CodeErrorMessages.EMPTY_VALUE;

            else if (valueAsString == "INVALID_EMAIL")
                return CodeErrorMessages.INVALID_EMAIL;

            else if (valueAsString == "INVALID_VALUE")
                return CodeErrorMessages.INVALID_VALUE;

            else if (valueAsString == "SHORT_PASSWORD")
                return CodeErrorMessages.SHORT_PASSWORD;

            else if (valueAsString == "SHORT_VALUE")
                return CodeErrorMessages.SHORT_VALUE;


            return "";
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            throw new Exception("it is not possible convert from target to source");
        }

    }
}